package com.akatsuki.studypulse.blueprint;

import com.akatsuki.studypulse.mental.AiJsonService;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.*;
import java.time.Instant;
import java.util.*;
import java.util.concurrent.*;
import org.springframework.beans.factory.annotation.*;
import org.springframework.stereotype.Service;

@Service
public class BlueprintJobService {
  private final Executor executor; private final Path runs; private final ObjectMapper mapper; private final AiJsonService ai; private final BlueprintValidator validator;
  private final Map<String, Job> jobs = new ConcurrentHashMap<>();
  public BlueprintJobService(@Qualifier("mentalModelTaskExecutor") Executor executor, @Value("${app.mental-model.runs-dir:runs}") String runs, ObjectMapper mapper, AiJsonService ai, BlueprintValidator validator) { this.executor=executor; this.runs=Path.of(runs); this.mapper=mapper; this.ai=ai; this.validator=validator; }
  public synchronized Status create(String runId) throws IOException {
    Path run = runs.resolve(runId); if (!Files.exists(run.resolve("approved-mental-model.json"))) throw new IllegalStateException("Approve the mental model before creating a blueprint");
    Job old=jobs.get(runId); if(old!=null && old.running()) throw new IllegalStateException("A blueprint job is already active");
    Job job=new Job(runId); jobs.put(runId,job); executor.execute(()->process(job)); return job.status();
  }
  public Status status(String runId) throws IOException { Job j=jobs.get(runId); if(j!=null)return j.status(); Path f=runs.resolve(runId).resolve("blueprint/status.json"); if(Files.exists(f)) return mapper.readValue(Files.readString(f),Status.class); throw new IllegalArgumentException("No blueprint job for run " + runId); }
  public JsonNode draft(String runId) throws IOException { return readRequired(runId,"blueprint/blueprint-draft.json"); }
  /** Drafts may be incomplete while a coach is authoring them; approval remains the hard gate. */
  public JsonNode save(String runId, JsonNode blueprint) throws IOException { Context c=context(runId); JsonNode report=validator.validate(blueprint,c.concepts,c.chunks); Path d=runs.resolve(runId).resolve("blueprint"); Files.createDirectories(d); write(d.resolve("blueprint-draft.json"), blueprint); write(d.resolve("blueprint-validation.json"),report); return report; }
  public JsonNode approve(String runId) throws IOException { JsonNode draft=draft(runId); Context c=context(runId); JsonNode report=validator.validate(draft,c.concepts,c.chunks); if(!report.path("valid").asBoolean()) throw new IllegalStateException("Blueprint cannot be approved: "+report.path("errors")); var approved=mapper.createObjectNode(); approved.put("revision",Instant.now().toEpochMilli()); approved.put("approvedAt",Instant.now().toString()); approved.set("blueprint",draft); approved.set("validation",report); write(runs.resolve(runId).resolve("blueprint/blueprint-approved.json"),approved); return approved; }
  private void process(Job job) { try { job.update("ANALYZING_DEPENDENCIES"); Context c=context(job.runId); job.update("CREATING_LEARNING_SEQUENCE"); JsonNode result; try { result=ai.generate(prompt(c)); } catch (Exception ignored) { result=fallback(c); } result=normalize(result,c); job.update("MAPPING_RESOURCES"); mapResources(result,c); job.update("VALIDATING_GRAPH"); JsonNode report=validator.validate(result,c.concepts,c.chunks); Path dir=runs.resolve(job.runId).resolve("blueprint"); Files.createDirectories(dir); long generation=Files.list(dir).filter(p->p.getFileName().toString().startsWith("generation-")).count()+1; write(dir.resolve("generation-"+generation+".json"),result); write(dir.resolve("blueprint-draft.json"),result); write(dir.resolve("blueprint-validation.json"),report); job.done(); write(dir.resolve("status.json"),job.status()); } catch(Exception e) { job.fail(e.getMessage()); try { Path d=runs.resolve(job.runId).resolve("blueprint"); Files.createDirectories(d); write(d.resolve("status.json"),job.status()); }catch(Exception ignored){} } }
  private Context context(String runId) throws IOException { Path r=runs.resolve(runId); JsonNode approved=readRequired(runId,"approved-mental-model.json").path("mentalModel"); Set<String> concepts=new LinkedHashSet<>(); var inventory=mapper.createArrayNode(); collect(approved, "core_entities", concepts,inventory); collect(approved,"actors",concepts,inventory); collect(approved,"entity_relationships",concepts,inventory); collect(approved,"main_workflows",concepts,inventory); collect(approved,"business_rules",concepts,inventory); collect(approved,"boundaries",concepts,inventory); if(concepts.isEmpty()){concepts.add("core_idea"); inventory.add(mapper.createObjectNode().put("id","core_idea").put("label",approved.path("core_idea").asText("Core idea")));} Set<String> chunks=new HashSet<>(); List<JsonNode> excerpts=new ArrayList<>(); Path f=r.resolve("chunks.jsonl"); if(Files.exists(f)) for(String l:Files.readAllLines(f)){JsonNode n=mapper.readTree(l); String id=n.path("chunkId").asText(n.path("chunk_id").asText()); if(!id.isBlank()){chunks.add(id);excerpts.add(n);}} return new Context(approved,concepts,chunks,inventory,excerpts); }
  private void collect(JsonNode model,String field,Set<String> ids,com.fasterxml.jackson.databind.node.ArrayNode inventory){ int i=0; for(JsonNode n:model.path(field)){String label=n.isTextual()?n.asText():n.path("name").asText(n.path("label").asText(n.path("description").asText())); if(!label.isBlank()){String id=(field+"_"+(++i)).replaceAll("[^a-zA-Z0-9_]","_");ids.add(id);inventory.add(mapper.createObjectNode().put("id",id).put("label",label).put("source_field",field));}} }
  private String prompt(Context c){return """
      Create a traceable lesson blueprint from this approved mental model only. Do not add domain facts.
      Use ONLY these concept IDs in concept_ids. This blueprint is a production brief, not lesson prose:
      a later AI must be able to write the lesson and generate assets without guessing what each block means.
      Return JSON with inferred_context, concept_graph (nodes,edges), blocks, edges, coverage_map, misconceptions, assessment_plan, warnings, open_design_questions.
      Every block requires id,title,type,objective,purpose,concept_ids,prerequisite_block_ids,learner_action,scaffold_level,evidence_of_learning,checkpoint,transition,duration_minutes,resource_plan,content_brief.
      content_brief requires overview only. overview is one detailed, multi-paragraph Vietnamese rich-text description which the coach edits in a single editor. It must explicitly say what the section will write and in what order. When the block needs an image, include a paragraph beginning "Hình cần tạo:" with the complete visual description, composition, required elements and labels. For a diagram or sequence, include "Diagram cần tạo:" followed by actors/nodes and every relationship or ordered message. For a simulation, include "Mô phỏng HTML cần tạo:" followed by initial state, visible UI, learner actions, state transitions, feedback and completion condition. Do not create separate asset fields or prompts.
      Types: orientation,explanation,diagram,sequence,comparison,worked_example,simulation,guided_practice,independent_practice,checkpoint,summary,transfer_task.
      Edges require from,to,type,rationale,concept_ids. Learning edges point prerequisite -> dependent and types requires,next,branch,converges,optional.
      CONCEPT INVENTORY:
      %s
      MENTAL MODEL:
      %s
      """.formatted(c.inventory.toPrettyString(),c.model.toPrettyString());}
  private JsonNode normalize(JsonNode b,Context c){ if(!b.isObject())throw new IllegalArgumentException("AI blueprint is not an object"); if(!b.has("blocks") || !b.path("blocks").isArray())throw new IllegalArgumentException("AI blueprint has no blocks"); for(JsonNode n:b.path("blocks")){ var block=(com.fasterxml.jackson.databind.node.ObjectNode)n; JsonNode plan=block.get("resource_plan"); if(plan==null || plan.isNull()) block.set("resource_plan",mapper.createArrayNode()); else if(plan.isObject()){var resources=mapper.createArrayNode();resources.add(plan);block.set("resource_plan",resources);} else if(!plan.isArray()) block.set("resource_plan",mapper.createArrayNode()); if(!block.path("content_brief").isObject()) block.set("content_brief",mapper.createObjectNode().put("overview",block.path("purpose").asText())); } if(!b.path("edges").isArray() || b.path("edges").isEmpty()){var edges=((com.fasterxml.jackson.databind.node.ObjectNode)b).putArray("edges"); JsonNode previous=null; for(JsonNode block:b.path("blocks")){if(previous!=null)edges.addObject().put("from",previous.path("id").asText()).put("to",block.path("id").asText()).put("type","next").put("rationale","Fallback display order").putArray("concept_ids");previous=block;}} return b; }
  private void mapResources(JsonNode b,Context c){ int i=0; for(JsonNode block:b.path("blocks")){var resources=(com.fasterxml.jackson.databind.node.ArrayNode)block.get("resource_plan"); if(resources.isEmpty()&&!c.excerpts.isEmpty()){JsonNode chunk=c.excerpts.get(i++%c.excerpts.size()); String id=chunk.path("chunkId").asText(chunk.path("chunk_id").asText()); resources.add(mapper.createObjectNode().put("type","source_excerpt").put("chunk_id",id).put("reason","Lexically relevant uploaded evidence"));} } }
  /** Safe minimal draft when the provider ignores the JSON-only instruction. */
  private JsonNode fallback(Context c){ var result=mapper.createObjectNode(); result.putObject("inferred_context").put("audience","Người mới có nền tảng cơ bản").put("estimated_duration_minutes",25).put("needs_review",true); var blocks=result.putArray("blocks"); int i=0; String previous=null; for(JsonNode concept:c.inventory){String id="block_"+(++i);var b=blocks.addObject();b.put("id",id).put("title",concept.path("label").asText()).put("type",i==1?"explanation":"guided_practice").put("objective","Explain and apply "+concept.path("label").asText()).put("purpose","");b.putObject("content_brief").put("needs_input",true).put("overview","").put("open_question","Coach must describe what this section will teach before approval.");b.putArray("concept_ids").add(concept.path("id").asText());b.putArray("prerequisite_block_ids");b.putArray("resource_plan"); if(previous!=null) b.withArray("prerequisite_block_ids").add(previous); previous=id;} var edges=result.putArray("edges"); for(int n=2;n<=i;n++)edges.addObject().put("from","block_"+(n-1)).put("to","block_"+n).put("type","requires").putArray("concept_ids"); result.putArray("concept_graph"); result.putObject("coverage_map"); result.putArray("warnings").add("Generated fallback because AI output was invalid; coach review required."); return result; }
  private JsonNode readRequired(String run,String rel)throws IOException{Path p=runs.resolve(run).resolve(rel);if(!Files.exists(p))throw new IllegalArgumentException("Missing artifact: "+rel);return mapper.readTree(Files.readString(p));}
  private void write(Path p,Object v)throws IOException{Files.writeString(p,mapper.writerWithDefaultPrettyPrinter().writeValueAsString(v),StandardCharsets.UTF_8);}
  private record Context(JsonNode model,Set<String> concepts,Set<String> chunks,JsonNode inventory,List<JsonNode> excerpts){}
  public record Status(String runId,String status,String stage,String error,Instant updatedAt){ }
  private static class Job {final String runId; volatile String status="QUEUED",stage="QUEUED",error; volatile Instant updatedAt=Instant.now(); Job(String id){runId=id;} boolean running(){return "QUEUED".equals(status)||"RUNNING".equals(status);} void update(String s){status="RUNNING";stage=s;updatedAt=Instant.now();}void done(){status="SUCCEEDED";stage="DONE";updatedAt=Instant.now();}void fail(String e){status="FAILED";stage="FAILED";error=e;updatedAt=Instant.now();} Status status(){return new Status(runId,status,stage,error,updatedAt);} }
}
