package com.akatsuki.studypulse.blueprint;

import com.akatsuki.studypulse.mental.AiJsonService;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.*;
import java.time.Instant;
import java.util.*;
import java.util.concurrent.*;
import org.springframework.beans.factory.annotation.*;
import org.springframework.stereotype.Service;

@Service
public class BlueprintJobService {
  private final Executor executor; private final Path runs; private final ObjectMapper mapper; private final AiJsonService ai; private final BlueprintValidator validator;
  private final Map<String, Job> jobs = new ConcurrentHashMap<>();
  public BlueprintJobService(@Qualifier("mentalModelTaskExecutor") Executor executor, @Value("${app.mental-model.runs-dir:runs}") String runs, ObjectMapper mapper, AiJsonService ai, BlueprintValidator validator) { this.executor=executor; this.runs=Path.of(runs); this.mapper=mapper; this.ai=ai; this.validator=validator; }
  public synchronized Status create(String runId) throws IOException {
    Path run = runs.resolve(runId); if (!Files.exists(run.resolve("approved-mental-model.json"))) throw new IllegalStateException("Approve the mental model before creating a blueprint");
    Job old=jobs.get(runId); if(old!=null && old.running()) throw new IllegalStateException("A blueprint job is already active");
    Job job=new Job(runId); jobs.put(runId,job); executor.execute(()->process(job)); return job.status();
  }
  public Status status(String runId) throws IOException { Job j=jobs.get(runId); if(j!=null)return j.status(); Path f=runs.resolve(runId).resolve("blueprint/status.json"); if(Files.exists(f)) return mapper.readValue(Files.readString(f),Status.class); throw new IllegalArgumentException("No blueprint job for run " + runId); }
  public JsonNode draft(String runId) throws IOException { return readRequired(runId,"blueprint/blueprint-draft.json"); }
  /** Drafts may be incomplete while a coach is authoring them; approval remains the hard gate. */
  public JsonNode save(String runId, JsonNode blueprint) throws IOException { Context c=context(runId); sanitizeConceptIds(blueprint,c.concepts); JsonNode report=validator.validate(blueprint,c.concepts,c.chunks); Path d=runs.resolve(runId).resolve("blueprint"); Files.createDirectories(d); write(d.resolve("blueprint-draft.json"), blueprint); write(d.resolve("blueprint-validation.json"),report); return report; }
  public JsonNode approve(String runId) throws IOException { JsonNode draft=draft(runId); Context c=context(runId); sanitizeConceptIds(draft,c.concepts); JsonNode report=validator.validate(draft,c.concepts,c.chunks); if(!report.path("valid").asBoolean()) throw new IllegalStateException("Blueprint cannot be approved: "+report.path("errors")); var approved=mapper.createObjectNode(); approved.put("revision",Instant.now().toEpochMilli()); approved.put("approvedAt",Instant.now().toString()); approved.set("blueprint",draft); approved.set("validation",report); write(runs.resolve(runId).resolve("blueprint/blueprint-draft.json"),draft); write(runs.resolve(runId).resolve("blueprint/blueprint-approved.json"),approved); return approved; }
  private void process(Job job) { try { job.update("ANALYZING_DEPENDENCIES"); Context c=context(job.runId); job.update("CREATING_LEARNING_SEQUENCE"); JsonNode result; try { result=ai.generate(prompt(c)); } catch (Exception error) { result=fallback(c,error.getMessage()); } result=normalize(result,c); job.update("DETAILING_LEARNING_BLOCKS"); enrichBlocks(result,c); job.update("MAPPING_RESOURCES"); mapResources(result,c); job.update("VALIDATING_GRAPH"); JsonNode report=validator.validate(result,c.concepts,c.chunks); Path dir=runs.resolve(job.runId).resolve("blueprint"); Files.createDirectories(dir); long generation=Files.list(dir).filter(p->p.getFileName().toString().startsWith("generation-")).count()+1; write(dir.resolve("generation-"+generation+".json"),result); write(dir.resolve("blueprint-draft.json"),result); write(dir.resolve("blueprint-validation.json"),report); job.done(); write(dir.resolve("status.json"),job.status()); } catch(Exception e) { job.fail(e.getMessage()); try { Path d=runs.resolve(job.runId).resolve("blueprint"); Files.createDirectories(d); write(d.resolve("status.json"),job.status()); }catch(Exception ignored){} } }
  private Context context(String runId) throws IOException { Path r=runs.resolve(runId); JsonNode approved=readRequired(runId,"approved-mental-model.json").path("mentalModel"); Set<String> concepts=new LinkedHashSet<>(); var inventory=mapper.createArrayNode(); collect(approved, "core_entities", concepts,inventory); collect(approved,"actors",concepts,inventory); collect(approved,"entity_relationships",concepts,inventory); collect(approved,"main_workflows",concepts,inventory); collect(approved,"business_rules",concepts,inventory); collect(approved,"boundaries",concepts,inventory); if(concepts.isEmpty()){concepts.add("core_idea"); inventory.add(mapper.createObjectNode().put("id","core_idea").put("label",approved.path("core_idea").asText("Core idea")));} Set<String> chunks=new HashSet<>(); List<JsonNode> excerpts=new ArrayList<>(); Path f=r.resolve("chunks.jsonl"); if(Files.exists(f)) for(String l:Files.readAllLines(f)){JsonNode n=mapper.readTree(l); String id=n.path("chunkId").asText(n.path("chunk_id").asText()); if(!id.isBlank()){chunks.add(id);excerpts.add(n);}} return new Context(approved,concepts,chunks,inventory,excerpts); }
  private void collect(JsonNode model,String field,Set<String> ids,com.fasterxml.jackson.databind.node.ArrayNode inventory){ int i=0; for(JsonNode n:model.path(field)){String label=n.isTextual()?n.asText():n.path("name").asText(n.path("label").asText(n.path("description").asText())); if(!label.isBlank()){String id=(field+"_"+(++i)).replaceAll("[^a-zA-Z0-9_]","_");ids.add(id);inventory.add(mapper.createObjectNode().put("id",id).put("label",label).put("source_field",field));}} }
  private String prompt(Context c){return """
      Create a traceable lesson blueprint from this approved mental model only. Do not add domain facts.
      Use ONLY these concept IDs in concept_ids. This blueprint is a production brief, not lesson prose:
      a later AI must be able to write the lesson and generate assets without guessing what each block means.
      Create 5 to 8 learning blocks, never one block per concept. Group related concept IDs in one coherent block; every concept ID must still appear in at least one block.
      This is the outline pass only. Return compact JSON with inferred_context, concept_graph (nodes,edges), blocks, edges, coverage_map, misconceptions, assessment_plan, warnings, open_design_questions.
      Every block requires id,title,type,objective,purpose,concept_ids,prerequisite_block_ids,learner_action,scaffold_level,evidence_of_learning,checkpoint,transition,duration_minutes,resource_plan. Keep purpose to one sentence. Do NOT return content_brief or any asset descriptions in this call; a separate call will detail each block.
      Types: orientation,explanation,diagram,sequence,comparison,worked_example,simulation,guided_practice,independent_practice,checkpoint,summary,transfer_task.
      Edges require from,to,type,rationale,concept_ids. Learning edges point prerequisite -> dependent and types requires,next,branch,converges,optional.
      CONCEPT INVENTORY:
      %s
      MENTAL MODEL:
      %s
      """.formatted(c.inventory.toPrettyString(),c.model.toPrettyString());}
  private void enrichBlocks(JsonNode blueprint,Context c){var warnings=((com.fasterxml.jackson.databind.node.ObjectNode)blueprint).withArray("warnings"); for(JsonNode node:blueprint.path("blocks")){var block=(com.fasterxml.jackson.databind.node.ObjectNode)node; try{JsonNode detail=ai.generate(detailPrompt(block,c));String overview=detail.path("overview").asText();if(overview.isBlank())throw new IllegalArgumentException("Detail call returned no overview");var brief=(com.fasterxml.jackson.databind.node.ObjectNode)block.get("content_brief");brief.put("overview",overview).put("needs_input",false);}catch(Exception error){warnings.add("Could not enrich block "+block.path("id").asText()+": "+error.getMessage());}}}
  private String detailPrompt(JsonNode block,Context c){var relevant=mapper.createArrayNode();Set<String> ids=new HashSet<>();block.path("concept_ids").forEach(id->ids.add(id.asText()));for(JsonNode concept:c.inventory)if(ids.contains(concept.path("id").asText()))relevant.add(concept);return """
      Write the detailed production brief for exactly one learning block in Vietnamese. Return JSON only: {"overview":"..."}.
      overview must fit in 3 or 4 short HTML paragraphs and stay under 650 visible Vietnamese characters. Remove generic introductions and repetition: state only what the eventual lesson section will explain, its order, what the learner should notice, and the bridge to the next section. This is a compact writing brief, not the finished lesson.
      Keep asset instructions compact but generation-ready, using semicolons instead of long prose. If the block needs an image, include a paragraph beginning exactly "Hình cần tạo:" with composition, required elements and labels. If it needs a diagram or sequence, include "Diagram cần tạo:" followed by actors/nodes and ordered messages in compact form. If it needs an HTML simulation, include "Mô phỏng HTML cần tạo:" followed by initial state, visible UI, actions, transitions, feedback and completion condition. Do not create separate fields.
      BLOCK:
      %s
      RELEVANT CONCEPTS:
      %s
      APPROVED MENTAL MODEL:
      %s
      """.formatted(block.toPrettyString(),relevant.toPrettyString(),c.model.toPrettyString());}
  private JsonNode normalize(JsonNode b,Context c){ if(!b.isObject())throw new IllegalArgumentException("AI blueprint is not an object"); if(!b.has("blocks") || !b.path("blocks").isArray())throw new IllegalArgumentException("AI blueprint has no blocks"); for(JsonNode n:b.path("blocks")){ var block=(com.fasterxml.jackson.databind.node.ObjectNode)n; JsonNode plan=block.get("resource_plan"); if(plan==null || plan.isNull()) block.set("resource_plan",mapper.createArrayNode()); else if(plan.isObject()){var resources=mapper.createArrayNode();resources.add(plan);block.set("resource_plan",resources);} else if(!plan.isArray()) block.set("resource_plan",mapper.createArrayNode()); if(!block.path("content_brief").isObject()) block.set("content_brief",mapper.createObjectNode().put("overview",block.path("purpose").asText())); } sanitizeConceptIds(b,c.concepts); if(!b.path("edges").isArray() || b.path("edges").isEmpty()){var edges=((com.fasterxml.jackson.databind.node.ObjectNode)b).putArray("edges"); JsonNode previous=null; for(JsonNode block:b.path("blocks")){if(previous!=null)edges.addObject().put("from",previous.path("id").asText()).put("to",block.path("id").asText()).put("type","next").put("rationale","Fallback display order").putArray("concept_ids");previous=block;}} return b; }
  /** AI may return IDs outside the approved inventory. Ignore those references instead of blocking the draft. */
  private void sanitizeConceptIds(JsonNode blueprint,Set<String> validConcepts){ for(JsonNode node:blueprint.path("blocks")){ if(!(node instanceof com.fasterxml.jackson.databind.node.ObjectNode block))continue; var filtered=mapper.createArrayNode(); for(JsonNode concept:block.path("concept_ids"))if(validConcepts.contains(concept.asText()))filtered.add(concept.asText()); block.set("concept_ids",filtered); } }
  private void mapResources(JsonNode b,Context c){ int i=0; for(JsonNode block:b.path("blocks")){var resources=(com.fasterxml.jackson.databind.node.ArrayNode)block.get("resource_plan"); if(resources.isEmpty()&&!c.excerpts.isEmpty()){JsonNode chunk=c.excerpts.get(i++%c.excerpts.size()); String id=chunk.path("chunkId").asText(chunk.path("chunk_id").asText()); resources.add(mapper.createObjectNode().put("type","source_excerpt").put("chunk_id",id).put("reason","Lexically relevant uploaded evidence"));} } }
  /** Safe minimal draft when the provider ignores the JSON-only instruction. */
  private JsonNode fallback(Context c,String reason){ var result=mapper.createObjectNode(); result.putObject("inferred_context").put("audience","Người mới có nền tảng cơ bản").put("estimated_duration_minutes",25).put("needs_review",true); Map<String,List<JsonNode>> groups=new LinkedHashMap<>(); for(JsonNode concept:c.inventory) groups.computeIfAbsent(concept.path("source_field").asText("core_entities"),ignored->new ArrayList<>()).add(concept); var blocks=result.putArray("blocks"); int i=0; String previous=null; for(var entry:groups.entrySet()){List<JsonNode> concepts=entry.getValue(); if(concepts.isEmpty())continue; String id="block_"+(++i),title=fallbackTitle(entry.getKey()),labels=concepts.stream().map(n->n.path("label").asText()).filter(s->!s.isBlank()).collect(java.util.stream.Collectors.joining(", ")); var b=blocks.addObject();b.put("id",id).put("title",title).put("type",i==1?"orientation":entry.getKey().equals("main_workflows")?"sequence":"explanation").put("objective","Hiểu "+title).put("purpose",fallbackBrief(title,labels));b.putObject("content_brief").put("needs_input",true).put("overview",fallbackBrief(title,labels)).put("open_question","AI blueprint fallback: coach nên rà soát và bổ sung asset nếu cần.");var ids=b.putArray("concept_ids");concepts.forEach(n->ids.add(n.path("id").asText()));b.putArray("prerequisite_block_ids");b.putArray("resource_plan"); if(previous!=null)b.withArray("prerequisite_block_ids").add(previous);previous=id;} var edges=result.putArray("edges"); for(int n=2;n<=i;n++)edges.addObject().put("from","block_"+(n-1)).put("to","block_"+n).put("type","requires").putArray("concept_ids"); result.putArray("concept_graph"); result.putObject("coverage_map"); result.putArray("warnings").add("Generated fallback because AI output was invalid: "+(reason==null?"unknown error":reason)); return result; }
  private String fallbackTitle(String field){return switch(field){case "actors"->"Các vai trò trong luồng";case "core_entities","entity_relationships"->"Thành phần và dữ liệu chính";case "main_workflows"->"Luồng xử lý theo từng bước";case "business_rules"->"Quy tắc cần tuân thủ";case "boundaries"->"Phạm vi và giới hạn";default->"Nội dung cần nắm";};}
  private String fallbackBrief(String title,String labels){return "<p>Phần này sẽ giải thích <strong>"+title+"</strong> bằng ngôn ngữ dễ hiểu, trước khi đi vào từng chi tiết. Người học cần hiểu phần này để theo dõi đúng các bước ở phần sau.</p><p>Nội dung sẽ lần lượt làm rõ: "+labels+". Mỗi ý sẽ được đặt trong đúng bối cảnh của luồng, không suy đoán thêm chi tiết ngoài dữ liệu đã được duyệt.</p><p>Cuối phần, bài viết sẽ nhắc lại điểm cần giữ lại và chuyển sang câu hỏi kế tiếp trong lộ trình học.</p>";}
  private JsonNode readRequired(String run,String rel)throws IOException{Path p=runs.resolve(run).resolve(rel);if(!Files.exists(p))throw new IllegalArgumentException("Missing artifact: "+rel);return mapper.readTree(Files.readString(p));}
  private void write(Path p,Object v)throws IOException{Files.writeString(p,mapper.writerWithDefaultPrettyPrinter().writeValueAsString(v),StandardCharsets.UTF_8);}
  private record Context(JsonNode model,Set<String> concepts,Set<String> chunks,JsonNode inventory,List<JsonNode> excerpts){}
  public record Status(String runId,String status,String stage,String error,Instant updatedAt){ }
  private static class Job {final String runId; volatile String status="QUEUED",stage="QUEUED",error; volatile Instant updatedAt=Instant.now(); Job(String id){runId=id;} boolean running(){return "QUEUED".equals(status)||"RUNNING".equals(status);} void update(String s){status="RUNNING";stage=s;updatedAt=Instant.now();}void done(){status="SUCCEEDED";stage="DONE";updatedAt=Instant.now();}void fail(String e){status="FAILED";stage="FAILED";error=e;updatedAt=Instant.now();} Status status(){return new Status(runId,status,stage,error,updatedAt);} }
}
